services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      API_KEY: "your_super_secret_email_guard_key_123" # Ensure this matches frontend
    # NO VOLUMES SECTION HERE FOR THE MODEL OR AI FOLDER!
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_KEY: "your_super_secret_email_guard_key_123"
      REACT_APP_BACKEND_URL: "http://backend:5000"
    depends_on:
      - backend
    restart: unless-stopped